[package]
name = "carbon-jito-protos"
version = "0.2.4"
edition = { workspace = true }
publish = false

[dependencies]
prost = { workspace = true }
prost-types = { workspace = true }
tonic = { workspace = true }

[build-dependencies]
protobuf-src = "1"
tonic-build = { workspace = true }